language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
- cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DTINYDNG_WERROR=ON
- cmake --build build --parallel 4
- ctest --test-dir build --output-on-failure
